name: Linkspector

on:
  push:
    branches: [ main, v1.x ]
    paths:
      - '**/*.md'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes' # report only only broken links, not valid ones
        use-verbose-mode: 'yes' # include HTTP status codes and error messages
        config-file: '.github/linters/.linkcheck.json'