name: Link Checker

on:
  push:
    branches: [ main, v1.x ]
    paths:
      - '**/*.md'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no' # report only only broken links, not valid ones
        use-verbose-mode: 'yes' # include HTTP status codes and error messages
        # config-file: '.github/linters/.linkcheck.json' # specify ignored links and other config
        check-modified-files-only: 'no' # only check links in files modified in the current PR or commit
        base-branch: 'v1.x' # the branch to compare against when determining modified files, typically the main development branch